name = "rental-price-tracker"
compatibility_date = "2024-03-20"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "rental_db"
database_id = "8e38a8cf-4df9-4d62-8910-fa4efd768d95"

[[r2_buckets]]
binding = "R2_CONTRACTS"
bucket_name = "rental-contracts"

