CREATE TABLE IF NOT EXISTS deleted_rentals (
  id TEXT PRIMARY KEY,
  city TEXT NOT NULL,
  district TEXT NOT NULL,
  address TEXT NOT NULL,
  type TEXT NOT NULL,
  layout TEXT NOT NULL,
  area REAL NOT NULL,
  floor TEXT NOT NULL,
  buildingAge INTEGER NOT NULL,
  price INTEGER NOT NULL,
  pricePerPyeong INTEGER NOT NULL,
  latitude REAL NOT NULL,
  longitude REAL NOT NULL,
  includesWater BOOLEAN NOT NULL,
  includesElectricity BOOLEAN NOT NULL,
  electricityBillingType TEXT DEFAULT 'taipower',
  electricityPricePerKwh REAL,
  electricitySummerPricePerKwh REAL,
  waterBillingType TEXT DEFAULT 'taiwater',
  waterPricePerUnit REAL,
  waterSummerPricePerUnit REAL,
  hasParking BOOLEAN NOT NULL,
  genderRestriction TEXT NOT NULL,
  equipments TEXT NOT NULL,
  features TEXT NOT NULL,
  transports TEXT NOT NULL,
  hasElevator BOOLEAN NOT NULL,
  canCook BOOLEAN NOT NULL,
  hasBalcony BOOLEAN NOT NULL,
  canMoveHuji BOOLEAN NOT NULL,
  canPet BOOLEAN NOT NULL,
  trashService BOOLEAN NOT NULL,
  canSubsidize BOOLEAN DEFAULT 0,
  approved BOOLEAN DEFAULT 0,
  contractFile TEXT,
  posterRole TEXT DEFAULT 'landlord',
  agencyFeeCharged BOOLEAN DEFAULT 0,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  deletedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id TEXT PRIMARY KEY,
  rentalId TEXT NOT NULL,
  action TEXT NOT NULL,
  role TEXT NOT NULL,
  ip TEXT NOT NULL,
  details TEXT,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);
